### ISSUE TITLE
Upgrading post office to 3.4.1 causes multiple emails to send

### ISSUE THREAD

**Issue by himynameistimli** [ui/django-post_office#330] opened 2020-08-17 01:10 UTC
Hi,

I'm having an issue that appeared after we upgraded to post office 3.4.1.

In our setup, we're using Django 3 and celery for sending emails after a certain period of time (we wait for additional information before deciding to send or cancel the emails). After a period of time, a custom task is called, which calls the `send_queued_mail` function.

With the upgrade to 3.4.1 I noticed that send_queued_mail was being called early (by itself) and multiple times, so my logs showed that emails were sent multiple times instantaneously. This occurred even when I didn't call my own task to call `send_queued_mail`.

It appears to be indeterministic, meaning it happened only happens occasionally.

Downgrading to 3.3.1 solved my problem, and the duplicated emails went away.

**Comment by fadedDexofan** [comment] 2020-09-15 14:21
https://github.com/ui/django-post_office/pull/333

**Comment by jrief** [comment] 2020-09-15 15:53
Did you limit the number of simultaneous connections to your SMTP server to 1?

**Comment by selwin** [comment] 2020-10-31 08:53
Duplicate of https://github.com/ui/django-post_office/issues/326 . See my comment [here](https://github.com/ui/django-post_office/pull/338#issuecomment-719905372). The TLDR is that the celery tasks should acquire a lock before sending emails.

**Closed by selwin** 2020-10-31 08:53 UTC
